### ISSUE TITLE
Kafka Topics are not getting created. I am using docker compose file in confluent-streams/labs/streams-writing

### ISSUE THREAD

**Issue by puravdani** [confluentinc/training-ksql-and-streams-src#33]
I have Mac OS and trying to run docker-compose in confluent-streams/labs/streams-writing

While creating topics using command,  kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic lines-topic, fails with below error

ouldn't resolve server kafka:9092 from bootstrap.servers as DNS resolution failed for kafka (org.apache.kafka.clients.ClientUtils)
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:479)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:61)
	at kafka.admin.TopicCommand$AdminClientTopicService$.createAdminClient(TopicCommand.scala:212)
	at kafka.admin.TopicCommand$AdminClientTopicService$.apply(TopicCommand.scala:216)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:57)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:89)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:48)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:439)
	... 5 more

**Comment by russau** [comment]
Hello puravdani,

This repository is only intended to be used as part of paid training from Confluent.  More details on our courses here: https://www.confluent.io/training/

**Comment by puravdani** [comment]
Absolutely, I am part of that training, which is virtual and trying to setup this on my machine as provided in instructions

**Comment by russau** [comment]
Please send an email to training-lab-support@confluent.io.
